language: cpp
compiler: gcc

addons:
  # Boost
  apt: 
    packages: libboost-all-dev

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Qt5 SVG
  - sudo apt-get install libqt5svg5-dev
  # Cairo
  - sudo apt install libcairo2-dev 

script: 
  - qmake -qt=qt5 divbox.pro
  - make -s debug

